name: digital_prescription
description: MNS 5376:2016 digital prescription prototype
publish_to: "none"
version: 0.1.1+2

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.19.0
  pdf: ^3.11.0
  printing: ^5.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/DejaVuSans.ttf
    - assets/images/med.png
